/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategicPartnerProgramRouteImport } from './routes/strategic-partner-program'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ServicioDeImplementacionRouteImport } from './routes/servicio-de-implementacion'
import { Route as IntegracionesRouteImport } from './routes/integraciones'
import { Route as CoreBancarioRouteImport } from './routes/core-bancario'
import { Route as Contact8RouteImport } from './routes/contact-8'
import { Route as CanalesDigitalesRouteImport } from './routes/canales-digitales'
import { Route as AnalisisDeDatosRouteImport } from './routes/analisis-de-datos'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const StrategicPartnerProgramRoute = StrategicPartnerProgramRouteImport.update({
  id: '/strategic-partner-program',
  path: '/strategic-partner-program',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicioDeImplementacionRoute =
  ServicioDeImplementacionRouteImport.update({
    id: '/servicio-de-implementacion',
    path: '/servicio-de-implementacion',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegracionesRoute = IntegracionesRouteImport.update({
  id: '/integraciones',
  path: '/integraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreBancarioRoute = CoreBancarioRouteImport.update({
  id: '/core-bancario',
  path: '/core-bancario',
  getParentRoute: () => rootRouteImport,
} as any)
const Contact8Route = Contact8RouteImport.update({
  id: '/contact-8',
  path: '/contact-8',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalesDigitalesRoute = CanalesDigitalesRouteImport.update({
  id: '/canales-digitales',
  path: '/canales-digitales',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisDeDatosRoute = AnalisisDeDatosRouteImport.update({
  id: '/analisis-de-datos',
  path: '/analisis-de-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analisis-de-datos': typeof AnalisisDeDatosRoute
  '/canales-digitales': typeof CanalesDigitalesRoute
  '/contact-8': typeof Contact8Route
  '/core-bancario': typeof CoreBancarioRoute
  '/integraciones': typeof IntegracionesRoute
  '/servicio-de-implementacion': typeof ServicioDeImplementacionRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/strategic-partner-program': typeof StrategicPartnerProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analisis-de-datos': typeof AnalisisDeDatosRoute
  '/canales-digitales': typeof CanalesDigitalesRoute
  '/contact-8': typeof Contact8Route
  '/core-bancario': typeof CoreBancarioRoute
  '/integraciones': typeof IntegracionesRoute
  '/servicio-de-implementacion': typeof ServicioDeImplementacionRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/strategic-partner-program': typeof StrategicPartnerProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analisis-de-datos': typeof AnalisisDeDatosRoute
  '/canales-digitales': typeof CanalesDigitalesRoute
  '/contact-8': typeof Contact8Route
  '/core-bancario': typeof CoreBancarioRoute
  '/integraciones': typeof IntegracionesRoute
  '/servicio-de-implementacion': typeof ServicioDeImplementacionRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/strategic-partner-program': typeof StrategicPartnerProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/analisis-de-datos'
    | '/canales-digitales'
    | '/contact-8'
    | '/core-bancario'
    | '/integraciones'
    | '/servicio-de-implementacion'
    | '/sobre-nosotros'
    | '/strategic-partner-program'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analisis-de-datos'
    | '/canales-digitales'
    | '/contact-8'
    | '/core-bancario'
    | '/integraciones'
    | '/servicio-de-implementacion'
    | '/sobre-nosotros'
    | '/strategic-partner-program'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/analisis-de-datos'
    | '/canales-digitales'
    | '/contact-8'
    | '/core-bancario'
    | '/integraciones'
    | '/servicio-de-implementacion'
    | '/sobre-nosotros'
    | '/strategic-partner-program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AnalisisDeDatosRoute: typeof AnalisisDeDatosRoute
  CanalesDigitalesRoute: typeof CanalesDigitalesRoute
  Contact8Route: typeof Contact8Route
  CoreBancarioRoute: typeof CoreBancarioRoute
  IntegracionesRoute: typeof IntegracionesRoute
  ServicioDeImplementacionRoute: typeof ServicioDeImplementacionRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  StrategicPartnerProgramRoute: typeof StrategicPartnerProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategic-partner-program': {
      id: '/strategic-partner-program'
      path: '/strategic-partner-program'
      fullPath: '/strategic-partner-program'
      preLoaderRoute: typeof StrategicPartnerProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicio-de-implementacion': {
      id: '/servicio-de-implementacion'
      path: '/servicio-de-implementacion'
      fullPath: '/servicio-de-implementacion'
      preLoaderRoute: typeof ServicioDeImplementacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integraciones': {
      id: '/integraciones'
      path: '/integraciones'
      fullPath: '/integraciones'
      preLoaderRoute: typeof IntegracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-bancario': {
      id: '/core-bancario'
      path: '/core-bancario'
      fullPath: '/core-bancario'
      preLoaderRoute: typeof CoreBancarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-8': {
      id: '/contact-8'
      path: '/contact-8'
      fullPath: '/contact-8'
      preLoaderRoute: typeof Contact8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canales-digitales': {
      id: '/canales-digitales'
      path: '/canales-digitales'
      fullPath: '/canales-digitales'
      preLoaderRoute: typeof CanalesDigitalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis-de-datos': {
      id: '/analisis-de-datos'
      path: '/analisis-de-datos'
      fullPath: '/analisis-de-datos'
      preLoaderRoute: typeof AnalisisDeDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AnalisisDeDatosRoute: AnalisisDeDatosRoute,
  CanalesDigitalesRoute: CanalesDigitalesRoute,
  Contact8Route: Contact8Route,
  CoreBancarioRoute: CoreBancarioRoute,
  IntegracionesRoute: IntegracionesRoute,
  ServicioDeImplementacionRoute: ServicioDeImplementacionRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  StrategicPartnerProgramRoute: StrategicPartnerProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
